#!/bin/bash

# init
apt update -y && apt upgrade -y; clear
apt install screenfetch -y; clear
apt install git -y
apt install nodejs -y

# header
clear
screenfetch
echo

# banner
echo -e "\x1b[0;93m[*] \x1b[0;92mAuthor \x1b[0;91m: \x1b[0;96mRiky Ripaldo"
echo -e "\x1b[0;93m[*] \x1b[0;92mGithub \x1b[0;91m: \x1b[3;95mhttps://github.com/RikyXDZ\x1b[0m"
sleep 1; echo

# body
echo -e "\x1b[1;93m[*] \x1b[0;92mInstalling Modules"
npm install
echo -e "\x1b[1;93m[*] \x1b[0;95mInstslling Successfully"
sleep 1
echo -e "\x1b[1;93m[*] \x1b[0;94Create File Script"
sleep 1

path='views/'
file='start'
load='..'

echo -e "\x1b[0;96mTo start the script please type ./start then enter"
sleep 5

cd $path
mv $file $load

sleep 1
# end
node index
